// userlogin
const USER_LOGIN = "USER_LOGIN";
const USER_ACCOUNTS = "USER_ACCOUNTS";
const ACC_WECON = "ACC_WECON";
const LOGIN_USER = "LOGIN_USER";
const WECON_LOGIN = "WECON_LOGIN";

export { USER_LOGIN, USER_ACCOUNTS, LOGIN_USER, ACC_WECON, WECON_LOGIN };
